name: noteapp
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  badges: ^2.0.3
  awesome_dialog: ^3.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_otp_text_field: ^1.1.1
  get_storage: ^2.0.3
  http: ^0.13.5
  image_picker: ^0.8.6
  internet_connection_checker: ^1.0.0+1
  lottie: ^1.4.3
  provider: ^6.0.3
  cross_file_image: ^1.0.0

  motion_toast: ^2.5.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/image/
    - lib/assets/image/sing.jpg
    - lib/assets/image/user.json
    - lib/assets/image/loading33.json
    - lib/assets/image/password.json
    - lib/assets/image/email.json
    - lib/assets/image/profilepic.jpg
    - lib/assets/image/notesbackground.jpg
    - lib/assets/image/nodata.json
    - lib/assets/image/waitingblue.json
    - lib/assets/fonts/en/
    - lib/assets/lang/ar.json
    - lib/assets/lang/en.json




    

  fonts:
    - family: Dancing
      fonts:
        - asset: lib/assets/fonts/en/DancingScript-Bold.ttf
    - family: oswalad
      fonts:
        - asset: lib/assets/fonts/en/Oswald-Regular.ttf
    - family: cairo
      fonts:
        - asset: lib/assets/fonts/ar/Cairo-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/ar/Cairo-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
